### ISSUE TITLE
Make the repo private for privacy and safety meassures

### ISSUE THREAD

**Issue by NULLYUKI** [PrincessAkira/usefull-shit#1]
How I understand this repo, it only hosts your config and other tweaks for your setup that only you use. So it would be better to set the repo to "private" instead of "public" 

But in case you are having this repo set to "public" so other people can use the configs and tweaks, then you can close this issue.

**Comment by HerXayah** [comment]
Indeed it is

**Comment by NULLYUKI** [comment]
> Indeed it is

@PrincessAkira ? What are you trying to say with "Indeed it is" could you please try to write a proper sentence instead of just "Indeed it is" or try to quote which sentence you mean. Like dafuq do you mean with that?

So let me try it again and maybe this time you can write a more proper sentence with more words.

How I understand this repo, it only hosts your config and other tweaks for your setup that only you use. So it would be better to set the repo to "private" instead of "public"

But in case you are having this repo set to "public" so other people can use the configs and tweaks, then you can close this issue.

**Comment by NULLYUKI** [comment]
So in my opinion this issue is still open, because I didn't received a CLEAR and proper answer from you and only a "indeed it is" that doesn't answer anything bruh

**Comment by NULLYUKI** [comment]
@PrincessAkira Still waiting for a clear answer.
